/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DrugInventoryWareHouse;

/**
 *
 * @author chandukongara
 */
public class DrugInventoryWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugInventoryWorkAreaPanel
     */
    public DrugInventoryWorkAreaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestTitle = new javax.swing.JLabel();
        btnReload = new javax.swing.JButton();
        spTableRequest = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnProcessRequest = new javax.swing.JButton();
        btnRequestStatus = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();

        lblRequestTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblRequestTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRequestTitle.setText("Requests From Clinics and Hospitals");

        btnReload.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnReload.setText("Reload");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Equipment Name", "Quantity", "Sender", "Receiver", "Urgency Level", "Requests Y/N"
            }
        ));
        spTableRequest.setViewportView(tblView);

        btnProcessRequest.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        btnRequestStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnRequestStatus.setText("View Request Status");

        btnAssign.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAssign.setText("Assign To Me");

        btnPrevious.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnPrevious.setText("Previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRequestTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcessRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRequestStatus)
                        .addGap(10, 10, 10)
                        .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spTableRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblRequestTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReload)
                    .addComponent(spTableRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessRequest)
                    .addComponent(btnRequestStatus)
                    .addComponent(btnAssign)
                    .addComponent(btnPrevious))
                .addContainerGap(292, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcessRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnRequestStatus;
    private javax.swing.JLabel lblRequestTitle;
    private javax.swing.JScrollPane spTableRequest;
    private javax.swing.JTable tblView;
    // End of variables declaration//GEN-END:variables
}
