/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorRole;

import Schema.Doctor.Doctor;
import Schema.Doctor.PrescriptionList;
import Schema.EcoSystem;
import Schema.Enterprise.Enterprise;
import Schema.Network.Network;
import Schema.Organization.DoctorOrganization;
import Schema.UserAccount.UserAccount;
import Schema.WorkQueue.DoctorWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lakshyagupta
 */
public class DoctorLandingPanel extends javax.swing.JPanel {
private JPanel userprocessContainer;
private DoctorOrganization docOrg;
private Enterprise ent;
private UserAccount ua;
private Doctor doc;
private PrescriptionList presList;
private DoctorWorkRequest docReq;
private Network ntw;
private EcoSystem system;

    /**
     * Creates new form DoctorLandingPanel
     */
public DoctorLandingPanel(JPanel userProcessContainer, UserAccount ua, DoctorOrganization docOrg, Enterprise ent, EcoSystem system, Network ntw) {
initComponents();
this.userprocessContainer=userProcessContainer;
this.ua=ua;
this.docOrg=docOrg;
this.ent=ent;
this.ntw=ntw;
this.system=system;
ntw();

    }/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prescriptionBtn = new javax.swing.JButton();
        medicalequipBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 47, 90));

        prescriptionBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        prescriptionBtn.setText("Write Prescription");
        prescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionBtnActionPerformed(evt);
            }
        });

        medicalequipBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        medicalequipBtn.setText("Order Medicine");
        medicalequipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalequipBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCTOR WORK AREA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(prescriptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(medicalequipBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescriptionBtn)
                    .addComponent(medicalequipBtn))
                .addGap(394, 394, 394))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void medicalequipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalequipBtnActionPerformed
CardLayout crd = (CardLayout) userprocessContainer.getLayout();
userprocessContainer.add("DoctorPrescPanel", new ui.DoctorRole.ClinicMedOrderPanel(userprocessContainer, ua, docOrg,ent,system,ntw));// TODO add your handling code here:
crd.next(userprocessContainer);
    }//GEN-LAST:event_medicalequipBtnActionPerformed

    private void prescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionBtnActionPerformed
CardLayout crd = (CardLayout) userprocessContainer.getLayout();
userprocessContainer.add("DoctorPrescPanel", new ui.DoctorRole.DoctorPrescPanel(userprocessContainer,presList,ua,ent,docOrg));// TODO add your handling code here:
crd.next(userprocessContainer);
    }//GEN-LAST:event_prescriptionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton medicalequipBtn;
    private javax.swing.JButton prescriptionBtn;
    // End of variables declaration//GEN-END:variables

    private void ntw() {
ntw.getName();
    }
}
