/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalAdminRole;

import Schema.Employee.Employee;
import Schema.Enterprise.Enterprise;
import Schema.Organization.Organization;
import Schema.Organization.OrganizationDirectory;
import Schema.Role.Role;
import Schema.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16176
 */
public class ManageUserAccountPanel extends javax.swing.JPanel {
    private JPanel userprocesscontainer;
    private Enterprise ent;
    

    /**
     * Creates new form ManageUserAccountPanel
     */
    public ManageUserAccountPanel(JPanel userprocessContainer, Enterprise ent) {
        initComponents();
        this.ent=ent;
        this.userprocesscontainer=userprocessContainer;
        
        populateOrgCmbBox();
        popData();
    }

        public void populateOrgCmbBox() {
orgCmbBox1.removeAllItems();
for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
orgCmbBox1.addItem(organization);
}
    }

        public void popData() {
DefaultTableModel model = (DefaultTableModel)  userTbl1.getModel();
model.setRowCount(0);
for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
Object row[] = new Object[2];
row[0] = ua.getUsername();
row[1] = ua.getRole();
((DefaultTableModel) userTbl1.getModel()).addRow(row);
}
}
    }
        
        
public void populateRoleCmbBox(Organization org) {
roleCmbBox1.removeAllItems();
for (Role role : org.getSupportedRole()){
roleCmbBox1.addItem(role);
}
    }

public void populateEmpCmbBox(Organization org) {
empCmbBox1.removeAllItems();
for (Employee emp : org.getEmployeeDirectory().getEmployeeList()){
empCmbBox1.addItem(emp);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        userTbl1 = new javax.swing.JTable();
        passwordLbl1 = new javax.swing.JLabel();
        usernameLbl1 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        passwordTxt1 = new javax.swing.JTextField();
        nameTxt1 = new javax.swing.JTextField();
        orgLbl1 = new javax.swing.JLabel();
        roleLbl1 = new javax.swing.JLabel();
        createuserBtn1 = new javax.swing.JButton();
        empCmbBox1 = new javax.swing.JComboBox();
        roleCmbBox1 = new javax.swing.JComboBox();
        orgCmbBox1 = new javax.swing.JComboBox();
        empLbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 47, 90));

        userTbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userTbl1);

        passwordLbl1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        passwordLbl1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl1.setText("Password      :");

        usernameLbl1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        usernameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl1.setText("Username    :");

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        passwordTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxt1ActionPerformed(evt);
            }
        });

        orgLbl1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        orgLbl1.setForeground(new java.awt.Color(255, 255, 255));
        orgLbl1.setText("Organization:");

        roleLbl1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        roleLbl1.setForeground(new java.awt.Color(255, 255, 255));
        roleLbl1.setText("Role:");

        createuserBtn1.setText("Create User Account");
        createuserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createuserBtn1ActionPerformed(evt);
            }
        });

        empCmbBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        roleCmbBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        orgCmbBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgCmbBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgCmbBox1ActionPerformed(evt);
            }
        });

        empLbl1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        empLbl1.setForeground(new java.awt.Color(255, 255, 255));
        empLbl1.setText("Employee:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage User Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(orgLbl1)
                                .addComponent(roleLbl1)
                                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(roleCmbBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orgCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(passwordLbl1)
                                    .addGap(18, 18, 18)
                                    .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(usernameLbl1)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(createuserBtn1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLbl1)
                            .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orgLbl1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(orgCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameLbl1)
                                .addComponent(nameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empLbl1)
                            .addComponent(empCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleLbl1)
                            .addComponent(roleCmbBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createuserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
 userprocesscontainer.remove(this);
 CardLayout lyt = (CardLayout) userprocesscontainer.getLayout();
lyt.previous(userprocesscontainer);// TODO add your handling code here:
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void passwordTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxt1ActionPerformed

    private void createuserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createuserBtn1ActionPerformed
String userName =   nameTxt1.getText();
String password = passwordTxt1.getText();
Organization org = (Organization) orgCmbBox1.getSelectedItem();
Employee emp = (Employee) empCmbBox1.getSelectedItem();
Role role = (Role) roleCmbBox1.getSelectedItem();
org.getUserAccountDirectory().createUserAccount(userName, password, emp, role);
popData();// TODO add your handling code here:
        
    }//GEN-LAST:event_createuserBtn1ActionPerformed

    private void orgCmbBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgCmbBox1ActionPerformed
Organization org = (Organization) orgCmbBox1.getSelectedItem();
if (org!=null){
populateEmpCmbBox(org);
populateRoleCmbBox(org);// TODO add your handling code here:
    }//GEN-LAST:event_orgCmbBox1ActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton createuserBtn1;
    private javax.swing.JComboBox empCmbBox1;
    private javax.swing.JLabel empLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt1;
    private javax.swing.JComboBox orgCmbBox1;
    private javax.swing.JLabel orgLbl1;
    private javax.swing.JLabel passwordLbl1;
    private javax.swing.JTextField passwordTxt1;
    private javax.swing.JComboBox roleCmbBox1;
    private javax.swing.JLabel roleLbl1;
    private javax.swing.JTable userTbl1;
    private javax.swing.JLabel usernameLbl1;
    // End of variables declaration//GEN-END:variables







}
